checks:
    php:
        code_rating: true
        duplication: true
        fix_php_opening_tag: false
        remove_php_closing_tag: true
        one_class_per_file: true
        side_effects_or_types: true
        no_mixed_inline_html: false
        require_braces_around_control_structures: false
        php5_style_constructor: false
        no_global_keyword: true
        avoid_usage_of_logical_operators: false
        psr2_class_declaration: true
        no_underscore_prefix_in_properties: true
        no_underscore_prefix_in_methods: true
        blank_line_after_namespace_declaration: true
        single_namespace_per_use: false
        psr2_switch_declaration: true
        psr2_control_structure_declaration: true
        avoid_superglobals: true
        security_vulnerabilities: true
        no_exit: true
filter: {  }
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=/tmp/myCoverage'
                coverage:
                    file: '/tmp/myCoverage'
                    format: 'clover'
