checks:
    php: true
filter: {  }
build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=/tmp/myCoverage'
                coverage:
                    file: '/tmp/myCoverage'
                    format: 'clover'
